### ISSUE TITLE
ENB

### ISSUE THREAD

**Issue by Zeblade777** [Charolas/PROJECT-SKYRIM#3]
"Unable to download enbseries_skyrimse_v0477.zip (HTTPDownloader+State|http://enbdev.com/enbseries_skyrimse_v0477.zip)"

If you try to use just this link it comes up "TRAP"

**Comment by Zeblade777** [comment]
went to https://build.wabbajack.org/authored_files just downloaded there.. why that works no clue

**Comment by Zeblade777** [comment]
Sorry I was wrong I just tried windows 10 and get the same error. Tried to get to discord but keep saying my invite was lol invalid.

**Comment by niggeb2000** [comment]
will not recognize enb 0477.zip even downloaded it .
